CREATE TABLE IF NOT EXISTS public.boards_kilter__climbs (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    layout_id int8 NOT NULL,
    name text NOT NULL,
    description text,
    frames text,
    generated boolean,
    created_at timestamptz DEFAULT now(),
    original_uuid text
);

CREATE TABLE IF NOT EXISTS public.boards_kilter__climb_stats (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    climb_id uuid NOT NULL REFERENCES public.boards_kilter__climbs(id) ON DELETE CASCADE,
    angle int8 NOT NULL,
    difficulty float8,
    ascension_count int8,
    quality float8,
    created_at timestamptz DEFAULT now()
);

-- Ensure UUID extension is enabled (needed for generating UUIDs)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Indexes for faster querying (optional)
CREATE INDEX idx_climb_id ON public.boards_kilter__climb_stats(climb_id);

CREATE TABLE IF NOT EXISTS public.boards_kilter__climb_feedback(
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    climb_id uuid NOT NULL REFERENCES public.boards_kilter__climbs(id) ON DELETE CASCADE,
    user_id int8 NOT NULL,
    type text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Indexes for faster querying (optional)
CREATE INDEX idx_user_id ON public.boards_kilter__climb_feedback(user_id);
CREATE INDEX idx_climb_id_feedback ON public.boards_kilter__climb_feedback(climb_id);

CREATE TABLE IF NOT EXISTS public.boards_kilter__climb_generation_metadata (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    climb_id uuid NOT NULL REFERENCES public.boards_kilter__climbs(id) ON DELETE CASCADE,
    temperature float8,
    prompt_frames text,
    top_p_sampling float8,
    created_at timestamptz DEFAULT now()
);
