import datetime
import uuid
from dataclasses import dataclass, field


class TableNames:
    climbs_table = "boards_kilter__climbs"
    climb_stats_table = "boards_kilter__climb_stats"
    climb_feedback_table = "boards_kilter__climb_feedback"
    generation_metadata_table = "boards_kilter__climb_generation_metadata"


class DictMixin:
    """Mixin class to add 'dict()' method for dataclasses."""
    def to_dict(self):
        return {k: v for k, v in self.__dict__.items()}


@dataclass
class KilterClimbStats(DictMixin):
    climb_id: str
    angle: int
    difficulty: int
    # ascension_count: int
    quality: float = 3  # TODO: seems, that we have nothing to do with that field
    # created_at: datetime.datetime = field(default_factory=datetime.datetime.now)


@dataclass
class KilterClimb(DictMixin):
    name: str
    frames: str
    layout_id: int = 1
    description: str = "Climb was generated by KilterGPT"  # TODO: come up with a "real" one
    generated: bool = True
    # created_at: datetime.datetime = field(default_factory=datetime.datetime.now)


@dataclass
class GenerationMetadata(DictMixin):
    climb_id: str
    prompt_frames: str
    temperature: float
    top_p_sampling: float
    # created_at: datetime.datetime = field(default_factory=datetime.datetime.now)


@dataclass
class GeneratedClimbFeedback(DictMixin):
    climb_id: str
    user_id: int
    type: str
    # created_at: datetime.datetime = field(default_factory=datetime.datetime.now)
